    include "resource.inc"

;global all the resources required by the fat12 directory
  if @DEF('FUNCLET')
    GLOBAL  RSRC_FUNCLET_MEDIAREADBOOTSECTOR
    GLOBAL  RSRC_FUNCLET_MEDIAUPDATE
    GLOBAL  RSRC_FUNCLET_PARSEDATABOOTSECTOR
    GLOBAL  RSRC_FUNCLET_MTXISSIGMATELFORMAT
    GLOBAL  RSRC_FUNCLET_FATCOUNTCX
    GLOBAL  RSRC_FUNCLET_FATCOUNTCXFAT12
    GLOBAL  RSRC_FUNCLET_FATCOUNTCXFAT16
    GLOBAL  RSRC_FUNCLET_HNDLFREE
    GLOBAL  RSRC_FUNCLET_FILESYSSETDIR
    GLOBAL  RSRC_FUNCLET_CHANGEDIR
    GLOBAL  RSRC_FUNCLET_FILESYSTEMPRESENT
    GLOBAL  RSRC_FUNCLET_FILESYSTEMTYPE
    GLOBAL  RSRC_FUNCLET_FILESYSTEMISREADY
    GLOBAL  RSRC_FUNCLET_FILEOPEN
    GLOBAL  RSRC_FUNCLET_FSOPEN
    GLOBAL  RSRC_FUNCLET_FILECLOSE
    GLOBAL  RSRC_FATWRITE_P_CODE
    GLOBAL  RSRC_FATWRITE_X_CODE
    GLOBAL  RSRC_FATWRITE_Y_CODE
    GLOBAL  RSRC_FUNCLET_SYSLOADFATWRITE
    GLOBAL  RSRC_FUNCLET_SEARCHDIR 
    GLOBAL  RSRC_FUNCLET_FS_DATADRIVEINIT
    GLOBAL  RSRC_FUNCLET_FS_GETDATADRIVEPBSLOCATION
    GLOBAL  RSRC_FUNCLET_FS_PARTITIONENTRYCOPY    
    GLOBAL  RSRC_FUNCLET_FSDATADRIVEGETSIZE
    GLOBAL  RSRC_FUNCLET_FSDATADRIVEGETSERIALNUMBER

    
  endif