    include "resource.inc"

;global all the resources required by the fat32 library
  if @DEF('FUNCLET')
;	GLOBAL RSRC_FUNCLET_FWD_RND    
;	GLOBAL RSRC_FUNCLET_FWD_ROUND    
;	GLOBAL RSRC_FUNCLET_FWD_LROUND    
;	GLOBAL RSRC_FUNCLET_AES_ENC_BLK    
;	GLOBAL RSRC_FUNCLET_INV_RND    
;	GLOBAL RSRC_FUNCLET_INV_LROUND    
;	GLOBAL RSRC_FUNCLET_INV_ROUND    
;	GLOBAL RSRC_FUNCLET_AES_DEC_BLK    
;	GLOBAL RSRC_FUNCLET_AES_ENC_KEY    
;	GLOBAL RSRC_FUNCLET_AES_DEC_KEY    
  	if !@DEF('MTP_FUNCLET')		
	GLOBAL RSRC_JANUSP_CODE 
	GLOBAL RSRC_JANUSX_CODE 
    GLOBAL RSRC_OEM_DATA
	GLOBAL RSRC_GPK_P
    GLOBAL RSRC_KEY_DATA
	GLOBAL RSRC_HDSIMPLCOMMON_P
	GLOBAL RSRC_HDSIMPL_P
	endif
    GLOBAL RSRC_AES_DEC_TABLE  
	GLOBAL RSRC_AES_KEY_TABLE
	GLOBAL RSRC_AES_ENC_TABLE
	GLOBAL RSRC_DOPLAY_P
	GLOBAL RSRC_JANUS_X
;	GLOBAL RSRC_JANUSY_CODE 
;	GLOBAL RSRC_AESTABLES_Y
    GLOBAL RSRC_FUNCLET_GETPRIVKEY
	
    

  ENDIF ;IF (!@def(resources))				       


