RSRC_MMCMEDIAINIT                      equ     0
RSRC_MMCMEDIAALLOCATE                  equ     0
RSRC_MMCMEDIADISCOVERALLOCATION        equ     0
RSRC_MMCMEDIAGETMEDIATABLE             equ     0
RSRC_MMCMEDIAGETINFO                   equ     0
RSRC_MMCMEDIAERASE                     equ     0

RSRC_MMCDATADRIVEINIT                  equ     0
RSRC_MMCDATADRIVEGETINFO               equ     0
RSRC_MMCDATADRIVESETINFO               equ     0
RSRC_MMCDATADRIVEREADSECTOR            equ     0
RSRC_MMCDATADRIVEWRITESECTOR           equ     0 
RSRC_MMCDATADRIVEMULTIWRITESETUP       equ     0 
RSRC_MMCDATADRIVEMULTIWRITESECTOR      equ     0 
RSRC_MMCDATADRIVEERASE                 equ     0 
RSRC_MMCDATADRIVEFLUSH                 equ     0 

