    include "resource.inc"

    GLOBAL RSRC_MMCMEDIAINIT
    GLOBAL RSRC_MMCMEDIAALLOCATE
    GLOBAL RSRC_MMCMEDIADISCOVERALLOCATION
    GLOBAL RSRC_MMCMEDIAGETMEDIATABLE
    GLOBAL RSRC_MMCMEDIAGETINFO
    GLOBAL RSRC_MMCMEDIAERASE
    
    GLOBAL RSRC_MMCDATADRIVEINIT             
    GLOBAL RSRC_MMCDATADRIVEGETINFO          
    GLOBAL RSRC_MMCDATADRIVESETINFO          
    GLOBAL RSRC_MMCDATADRIVEREADSECTOR       
    GLOBAL RSRC_MMCDATADRIVEWRITESECTOR      
    GLOBAL RSRC_MMCDATADRIVEMULTIWRITESETUP  
    GLOBAL RSRC_MMCDATADRIVEMULTIWRITESECTOR 
    GLOBAL RSRC_MMCDATADRIVEERASE            
    GLOBAL RSRC_MMCDATADRIVEFLUSH            
    
	GLOBAL RSRC_MMCENUMERATE
    GLOBAL RSRC_MMC_RESETDEVICE
    GLOBAL RSRC_MMC_PROCESSCSD
    GLOBAL RSRC_MMC_PROCESSCID
    GLOBAL RSRC_FUNCLET_MMCPROCESSCID2
    GLOBAL RSRC_MMC_DETECTPRESENCE
    GLOBAL RSRC_MMCSERIALNUMBERINIT
	GLOBAL RSRC_MMC_CHECKWRITEPROTECT
    
    GLOBAL RSRC_FUNCLET_MMC_TEST_ERASE
    GLOBAL RSRC_FUNCLET_MMC_HALINIT
