    include "resource.inc"

;global all the resources required by the fat32 library
  if @DEF('FUNCLET')
  
   GLOBAL  RSRC_JANUS_COMMON
   GLOBAL  RSRC_JANUS_MTP
   GLOBAL  RSRC_PKCRYPTO_P
   GLOBAL  RSRC_JANUSY_CONST
   GLOBAL  RSRC_JANUSY_DATA
   GLOBAL  RSRC_JANUS_TABLES
   GLOBAL  RSRC_JANUSX_CONST
   GLOBAL  RSRC_JANUS_COMMON_CONST
   GLOBAL  RSRC_AES_ENC_P
   GLOBAL  RSRC_JANUS_SUPPORT
   GLOBAL  RSRC_JANUS_COMMON
   GLOBAL  RSRC_JANUS_TABLES
   GLOBAL  RSRC_FATWRITE_P_CODE
   GLOBAL  RSRC_WRITEP
   GLOBAL  RSRC_MTPBOOTINIT
   GLOBAL  RSRC_TYPE_DATA
   GLOBAL  RSRC_MTP_HDS_NONOVL
   GLOBAL  RSRC_AES_DEC_P
   GLOBAL  RSRC_MTP_DRMHDS_IMPL_P
   GLOBAL  RSRC_MTP_DATABASE_P
   GLOBAL  RSRC_MTP_DRMMD5_P
   GLOBAL  RSRC_RESTORESYSDRIVE_P_CODE

  ENDIF ;IF (!@def(resources))				       


