RSRC_NANDMEDIAINIT                              equ     0
RSRC_NANDMEDIAALLOCATE                          equ     0
RSRC_NANDMEDIADISCOVERALLOCATION                equ     0
RSRC_NANDMEDIAGETMEDIATABLE                     equ     0
RSRC_NANDMEDIAGETINFO                           equ     0
RSRC_NANDMEDIAERASE                             equ     0

RSRC_NANDDATADRIVEINIT                          equ     0
RSRC_NANDDATADRIVEGETINFO                       equ     0
RSRC_NANDDATADRIVESETINFO                       equ     0
RSRC_NANDDATADRIVEREADSECTOR                    equ     0
RSRC_NANDDATADRIVEWRITESECTOR                   equ     0 
RSRC_NANDDATADRIVEDUMBMULTIWRITESETUP           equ     0 
RSRC_NANDDATADRIVEDUMBMULTIWRITESECTOR          equ     0 
RSRC_NANDDATADRIVECACHEMULTIWRITESETUP          equ     0 
RSRC_NANDDATADRIVECACHEMULTIWRITESECTOR         equ     0 
RSRC_NANDDATADRIVEERASE                         equ     0 
RSRC_NANDDATADRIVEFLUSH                         equ     0 

RSRC_NANDSYSTEMDRIVEINIT                        equ     0 
RSRC_NANDSYSTEMDRIVEGETINFO                     equ     0  
RSRC_NANDSYSTEMDRIVESETINFO                     equ     0  
RSRC_NANDSYSTEMDRIVEREADSECTOR                  equ     0 
RSRC_NANDSYSTEMDRIVEWRITESECTOR                 equ     0 
RSRC_NANDSYSTEMDRIVEMULTIWRITESETUP             equ     0 
RSRC_NANDSYSTEMDRIVEMULTIWRITESECTOR            equ     0 
RSRC_NANDSYSTEMDRIVEERASE                       equ     0 
RSRC_NANDSYSTEMDRIVEFLUSH                       equ     0 
