    include "resource.inc"

    GLOBAL RSRC_RAMMEDIAINIT
    GLOBAL RSRC_RAMMEDIAALLOCATE
    GLOBAL RSRC_RAMMEDIADISCOVERALLOCATION
    GLOBAL RSRC_RAMMEDIAGETMEDIATABLE
    GLOBAL RSRC_RAMMEDIAGETINFO
    GLOBAL RSRC_RAMMEDIAERASE
    
    GLOBAL RSRC_RAMDATADRIVEINIT             
    GLOBAL RSRC_RAMDATADRIVEGETINFO          
    GLOBAL RSRC_RAMDATADRIVESETINFO          
    GLOBAL RSRC_RAMDATADRIVEREADSECTOR       
    GLOBAL RSRC_RAMDATADRIVEWRITESECTOR      
    GLOBAL RSRC_RAMDATADRIVEMULTIWRITESETUP  
    GLOBAL RSRC_RAMDATADRIVEMULTIWRITESECTOR 
    GLOBAL RSRC_RAMDATADRIVEERASE            
    GLOBAL RSRC_RAMDATADRIVEFLUSH            
    
    GLOBAL RSRC_RAMSYSTEMDRIVEINIT             
    GLOBAL RSRC_RAMSYSTEMDRIVEGETINFO          
    GLOBAL RSRC_RAMSYSTEMDRIVESETINFO          
    GLOBAL RSRC_RAMSYSTEMDRIVEREADSECTOR       
    GLOBAL RSRC_RAMSYSTEMDRIVEWRITESECTOR      
    GLOBAL RSRC_RAMSYSTEMDRIVEMULTIWRITESETUP  
    GLOBAL RSRC_RAMSYSTEMDRIVEMULTIWRITESECTOR 
    GLOBAL RSRC_RAMSYSTEMDRIVEERASE            
    GLOBAL RSRC_RAMSYSTEMDRIVEFLUSH            
    