    include "resource.inc"

;global all the resources required by the serialnumber directory

    GLOBAL  RSRC_FUNCLET_CHIPSERIALNUMBERINIT
    GLOBAL  RSRC_FUNCLET_INTERNALMEDIASERIALNUMBERINIT
    GLOBAL  RSRC_FUNCLET_CHIPGETSERIALNUMBER
    GLOBAL  RSRC_FUNCLET_CREATENULLSERIALNUMBER
    GLOBAL  RSRC_FUNCLET_CONVERTHEXTOASCII
