#AS_OPTS=$(AS_OPTS) $(INC_ALL) -OJMNPRS -RDRS -gs -l -LCeIn -DTASKING $(BLD) 
AS_OPTS=$(INC_ALL) -OJMPS  -l -LCeIn -DTASKING $(BLD) 
#LK_OPTS=$(LK_OPTS) -L$(PRODLIB_DIR) -L$(MP3_PATH)\tasking -L$(BIN_DRIVE)\2410\lib\2410 -w8
LC_OPTS=$(LC_OPTS)
#CC_OPTS=$(CC_OPTS)  -Wc-s -w68 -w66 $(INC_ALL_C) -Wa$(INC_ALL) $(BLD) -DASCII_ONLY 
CC_OPTS=$(CC_OPTS) -Wc-s  $(BLD) -w68 -w66 $(INC_ALL_C) -Wa$(INC_ALL) 
