;******************************************************************************
; Copyright(C) SigmaTel, Inc. 2000/2001
;
; STMP Foreground Module Includes
;
;******************************************************************************

EffBufIdenticalOffset     equ        1
EffSrcDescrOffset         equ        2
EffSinkDescrOffset        equ        3
EffRoutine_Offset         equ        4
EffParameter0_Offset      equ        5
EffParameter1_Offset      equ        6
FGndModuleEntrySize       equ        7

FgndWorkBufSize           equ        $40
