#ifndef _MEDIADETECTION_H
#define _MEDIADETECTION_H

#define MEDIA_DETECT_POSITIVE_POLARITY  0
#define MEDIA_DETECT_NEGATIVE_POLARITY  1

#define MEDIA_TYPE_SMARTMEDIA   0
#define MEDIA_TYPE_MMC          1

//#ifndef NUM_REMOVABLE_MEDIA
//#define NUM_REMOVABLE_MEDIA 1
//#endif

#endif // #ifndef _MEDIADETECTION_H