;///////////////////////////////////////////////////////////////////////////////
; Copyright(C) SigmaTel, Inc. 2000/2001
;
; Mixer Module       
;///////////////////////////////////////////////////////////////////////////////

    IF (!@def(mixerequ))
mixerequ   equ     1

msFadeOut                    equ     2      ; number of milliseconds for the MixerMasterFadeOut
msFadeIn                     equ     2      ; number of milliseconds for the MixerMasterFadeIn

    ENDIF