#ifndef _SETTINGS_MENU_H
#define _SETTINGS_MENU_H

// menus in settings menu
// defines order of selection
#define SETTINGSMENU_FIRST  0

enum _MENUSETTING_ID
{
MENU_EQ = 0,
MENU_PLAYMODE,
MENU_CONTRAST,
MENU_PWRSAVINGS,
#ifdef BACKLIGHT
MENU_BACKLIGHT,
#endif
MENU_RECORD_SETTINGS,
MENU_SET_TIME,
MENU_SET_DATE,
 #ifdef WOW
MENU_WOW,
 #endif
MENU_SETTINGS_EXIT
#ifndef BACKLIGHT
,MENU_BACKLIGHT
#endif
};

#define SETTINGSMENU_LAST   MENU_SETTINGS_EXIT
#define SETTINGSMENU_COUNT  (SETTINGSMENU_LAST+1)
	
#ifdef S6B33B0A_LCD
#define SETTINGSMENU_PAGE1_COUNT	SETTINGSMENU_COUNT
#endif

#ifdef SED15XX_LCD
#define SETTINGSMENU_PAGE1_COUNT	4
#endif

#endif