    include "resource.inc"
    
    GLOBAL RSRC_NANDMEDIAINIT
    GLOBAL RSRC_NANDMEDIAALLOCATE
    GLOBAL RSRC_NANDMEDIADISCOVERALLOCATION
    GLOBAL RSRC_NANDMEDIAGETMEDIATABLE
    GLOBAL RSRC_NANDMEDIAGETINFO
    GLOBAL RSRC_NANDMEDIAERASE
    
    GLOBAL RSRC_NANDDATADRIVEINIT             
    GLOBAL RSRC_NANDDATADRIVEGETINFO          
    GLOBAL RSRC_NANDDATADRIVESETINFO          
    GLOBAL RSRC_NANDDATADRIVEREADSECTOR       
    GLOBAL RSRC_NANDDATADRIVEWRITESECTOR      
    GLOBAL RSRC_NANDDATADRIVEMULTIWRITESETUP  
    GLOBAL RSRC_NANDDATADRIVEMULTIWRITESECTOR 
    GLOBAL RSRC_NANDDATADRIVEERASE            
    GLOBAL RSRC_NANDDATADRIVEFLUSH            
    
    GLOBAL RSRC_NANDSYSTEMDRIVEINIT             
    GLOBAL RSRC_NANDSYSTEMDRIVEGETINFO          
    GLOBAL RSRC_NANDSYSTEMDRIVESETINFO          
    GLOBAL RSRC_NANDSYSTEMDRIVEREADSECTOR       
    GLOBAL RSRC_NANDSYSTEMDRIVEWRITESECTOR      
    GLOBAL RSRC_NANDSYSTEMDRIVEMULTIWRITESETUP  
    GLOBAL RSRC_NANDSYSTEMDRIVEMULTIWRITESECTOR 
    GLOBAL RSRC_NANDSYSTEMDRIVEERASE            
    GLOBAL RSRC_NANDSYSTEMDRIVEFLUSH            
