
RSRC_FONT_TABLE                 equ 0  ;$FILENAME font_table.src
RSRC_PDM                        equ 0  ;$FILENAME iso8859_PDM.src
RSRC_SDMS                       equ 0  ;$FILENAME iso8859_SDMs.src
RSRC_PGM_8                      equ 0  ;$FILENAME sigmatel_8_PGM.src
RSRC_SGMS_8                     equ 0  ;$FILENAME sigmatel_8_SGMs.src
RSRC_SCRIPTS_8                  equ 0  ;$FILENAME sigmatel_8_scripts.src
RSRC_SCRIPT_00_8                equ 0  ;$FILENAME sigmatel_8_script_00.src
RSRC_LCD_INIT_SEQ               equ 0  ;$FILENAME system_lcd_init_seq.src

