#!/usr/bin/perl -w
# CheckBuild - check files generated by sdkbuildall to a published file.
# The desired file is passed in as a command line paramter.

print "\n-->Comparing sdkbuildall output to that specified in txt file\n\n";
#$FileInput = "SDKBA_Expected.txt";      #temporary use - debugging.
# We now pass in a file using the command line

#open(IN,"<$FileInput") || die("cannot open file $! \n"); #temp use - debugging.
my $ExpectedFiles = shift @ARGV;
# my $OutputDirName = shift @ARGV;


if ($ExpectedFiles)
{

   open(IN,"<$ExpectedFiles") || die("cannot open Expected Files $! \n"); #temp use - debugging.
   
   while (<IN>)     # temporary use for debugging.
   {
      $line = $_;    # grab current line
      # test to see if this line is a comment line, if so skip it.
      unless ($line =~ /#/)
      {
         print "Opening File $line";
   
         # if there is an error opening file, we know that file wasn't built properly.
         open(FILE,"<$line") or die "\nXXXX Error - Problem opening $line \t -> $! \n";
         # the following is a hack to prevent a perl warning.
         $trash = <FILE>;
         $trash = $trash.2;
         # end of hack.
      }
   }
} else
{
   print "Error Expected Input file not included in parameter line\n"
}
print "\n";       #Just one more line feed.
